/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReaderService } from "../reader.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReaderCreateInput } from "./ReaderCreateInput";
import { Reader } from "./Reader";
import { ReaderFindManyArgs } from "./ReaderFindManyArgs";
import { ReaderWhereUniqueInput } from "./ReaderWhereUniqueInput";
import { ReaderUpdateInput } from "./ReaderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReaderControllerBase {
  constructor(
    protected readonly service: ReaderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reader })
  @nestAccessControl.UseRoles({
    resource: "Reader",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReader(@common.Body() data: ReaderCreateInput): Promise<Reader> {
    return await this.service.createReader({
      data: data,
      select: {
        createdAt: true,
        id: true,
        ratingsGiven: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reader] })
  @ApiNestedQuery(ReaderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reader",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async readers(@common.Req() request: Request): Promise<Reader[]> {
    const args = plainToClass(ReaderFindManyArgs, request.query);
    return this.service.readers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        ratingsGiven: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reader })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reader",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reader(
    @common.Param() params: ReaderWhereUniqueInput
  ): Promise<Reader | null> {
    const result = await this.service.reader({
      where: params,
      select: {
        createdAt: true,
        id: true,
        ratingsGiven: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reader })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reader",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReader(
    @common.Param() params: ReaderWhereUniqueInput,
    @common.Body() data: ReaderUpdateInput
  ): Promise<Reader | null> {
    try {
      return await this.service.updateReader({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          ratingsGiven: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reader })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reader",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReader(
    @common.Param() params: ReaderWhereUniqueInput
  ): Promise<Reader | null> {
    try {
      return await this.service.deleteReader({
        where: params,
        select: {
          createdAt: true,
          id: true,
          ratingsGiven: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
